=== AWKrol/wiremock/src/test/resources/jsonSchema/getUserIdSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "User",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "pattern": "^.*$"
    },
    "course": {
      "type": "string",
      "pattern": "^.*$"
    },
    "email": {
      "type": "string",
      "pattern": "\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*\\.\\w{2,4}"
    },
    "age": {
      "type": "integer",
      "minimum": 16,
      "maximum": 100
    }
  },
  "additionalProperties": false,
  "required": [
    "name",
    "email",
    "age"
  ]
}

=== AWKrol/wiremock/src/test/resources/__files/json/userGetAllResponse.json
[
  {
    "name":"Test user One",
    "course":"QA",
    "email":"testOne@test.test",
    "age": 23
  },
  {
    "name":"Test user Two",
    "course":"AQA",
    "email":"testTwo@test.test",
    "age": 23
  },
  {
    "name":"Test user Three",
    "course":"Dev",
    "email":"testThree@test.test",
    "age": 23
  }
]
